### ISSUE TITLE
Error on implicitly/externally declared types

### ISSUE THREAD

**Issue by akberg** [babyraging/yash#12]
Hi!

Some questions on implicit declarations 

* Yash is reporting error "symbol not declared" on the INITIAL state, which is implicitly declared. 

* YYSTATE can be defined in gcc flags, and is implicitly resolved by bison/yacc, but non-terminals with undeclared types are flagged as errors. 

Is there a way of allowing these thing in the extension settings, or is it an issue?

**Comment by babyraging** [comment]
Hi!

You are right, these can be both an issue or a new feature that can be added.
If you don't mind, can you provide me a minimal example of these problems?

Thanks.

**Comment by akberg** [comment]
Sure!

## lex/flex
![bilde](https://user-images.githubusercontent.com/25877966/109888768-5d6ec580-7c84-11eb-9b62-379d67fb1bc3.png)

The INITIAL state should be accepted by default, I think, as it is by definition implicitly declared.
The screenshot also captures that `%state` is highlighted wrong (keyword synonymous to `%s`).
<details>
<summary>code as text:</summary>

```lex
// scanner.l
%state COMMENT

%%
<INITIAL>\/\/ { BEGIN(COMMENT); }
<COMMENT>\n { BEGIN(INITIAL); }
%%
```
</details>

## Yacc/bison
![bilde](https://user-images.githubusercontent.com/25877966/109890757-213d6400-7c88-11eb-91be-076b26276dce.png)


This screenshot captures the error message on the implicitly typed non-terminal, which only appears when its value is accessed with `$$` (nice detail!). This one would maybe do as a setting, where one could turn this checking completely off, or tell the language server about the external declaration? Would be really nice if the `number` token etc. was recognized from outside as a `node_t*`.

<details>
<summary>full code as text </summary>

```lex
// parser.y
%{
#include <stdint.h>
#include <stdlib.h>

int yyerror ( const char *error );
extern int yylineno;
extern int yylex ( void );
extern char yytext[];

typedef enum { NUMBER_DATA, EXPRESSION, PROGRAM } node_index_t;
typedef struct n {
    node_index_t type;
    void *data;
    size_t n_children;
    struct n **children;
} node_t;

node_t* node_create(node_index_t type, void *data, size_t n_children, ...);
node_t* root;
%}

%token NUMBER
%left '+' '-'

%%
program : 
    expression { root = node_create(PROGRAM, (void*)0, 1, $1); }
    ;
expression :
    number '+' number { $$ = node_create(EXPRESSION, strdup("+"), 2, $1, $2); }
    ;
number : 
    NUMBER { $$ = node_create(NUMBER_DATA, strdup(yytext), 0); };
%%
int yyerror(const char *error)
{
    printf("%s on line %d: unexpected symbol `%s`\n", error, yylineno, yytext);
    exit(1);
}
```
</details>


This won't link, but will compile with gcc flag `-DYYSTYPE="node_t *"`:

Apart from this, the extension is doing a great impression. Thanks!

**Comment by babyraging** [comment]
Hi there, sorry for the late response.

The first part is actually an issue, thanks for finding it! It will be fixed in the next patch.

The second part can be added as a new feature.  
> Would be really nice if the number token etc. was recognized from outside as a node_t*.

This would be nice but I think there is not a naive solution to this right now. To be able to detect a implicitly typed non-terminal, we would need to manually parse the C code, which can include layers of included headers. That would be overkill, I would like to keep the extension simple.

If in the future, the C++ extension exposes to us means to use their language server outside of their extension, then we can do more sophiscated analysis.

If I remember correctly, Bison won't compile the code if a non-terminal is not typed and it is used inside actions right? Or you would need to declare it with compiler flag, like you did.

We could add a new setting named, I don't know, YYSTYPE? And if it is not specified, it will show the error message if a non-terminal is not typed (same as before); if it is specified, then the error will be ignored. What do you think?

**Comment by akberg** [comment]
> The first part is actually an issue, thanks for finding it! It will be fixed in the next patch.
That's great!

I can see the problems with overhead if the C extensions does not expose types. Actually, I don't even think the C extension has a way of detecting compile time flags from a makefile? 

> We could add a new setting named, I don't know, YYSTYPE? And if it is not specified, it will show the error message if a non-terminal is not typed (same as before); if it is specified, then the error will be ignored. What do you think?

A YYSTYPE setting for just deactivating type-error checking on tokens and non-terminals would be a neat first iteration! 

It could maybe be extended to a type definition (like the -D flag) whenever the C extension will allow you to read it? Or maybe the other way, is it possible to pass a type definition for `$$` to the C language server and let it do the type checking?

**Comment by babyraging** [comment]
Sorry again for the late response :), was being busy IRL.

The newer version is published and it shoul've solved these problems. 
I've added a YYTYPE setting, you can use that to disable the error and it will give type hint something like this:

![image](https://user-images.githubusercontent.com/14004642/111224977-74e07380-85df-11eb-9b5b-d125b151b480.png)

Check it out and if there are more issues (I hope not XD), be my guest to create new issues.

Thanks again for the issue.

**Comment by akberg** [comment]
Works great, good job!
