### ISSUE TITLE
Specific Grammar Syntax makes vscode (with wsl 2 + ubuntu) close remote connection constantly

### ISSUE THREAD

**Issue by ErickHernandez** [babyraging/yash#13]
Hi, I found that a specific grammar syntax is making that my vs code remote connection crash, if I remove that specific "code" it works. I tested uninstalling your extension and the problem dissapeared, after that I reinstalled your extension and removed that part  "code" from my .y file and it stopped closing my remote connection to ubuntu. Also I noticed that the problem occured only if I had the .y file with that "code" open.  Versions I tried with the same issue: 0.2.7 and 0.2.6.

The "code":

``statement: ID arraypos_or_params ’<-’ expr
          | llamar ID [ "(" [ {<expr>}+, ] ")" ]
          | escriba {<argument>}+,
          | lea {<lvalue>}+,
          | retorne optional_expr
          | if_statement
          | "mientras" expr optional_eol "haga" EOL statement_list EOL "fin" "mientras"
          | "repita" EOL statement_list EOL "hasta" expr
          | "para" <lvalue> "<-" expr "hasta" expr "haga" EOL statement_list EOL "fin" "para"``

**Comment by babyraging** [comment]
Hi! I tried to copy-past your code in VSCode with WSL 2 + Ubuntu, it didn't close the remote connection for me, maybe I was doing something wrong....

Can you provide me the minimum working complete example? 

Try to use the
\`\`\`yacc

\`\`\`
markdwon syntax to get this effect

```yacc
%{
#include <stdint.h>
#include <stdlib.h>
%}

%token NUMBER
%left '+' '-'

%%
example: NUMBER '+' NUMBER

%%
```

**Comment by babyraging** [comment]
I did a very simple test, and it showed that the crash is caused by these characters `’<-’`. By deleting or changing the quotes, it doesn't close the remote connection anymore. I think it is a plugin bug and it is not acceptable.

I'll dig into the details later. In the meanwhile, the simple fix is to change the quotes.

**Comment by babyraging** [comment]
This is actually a critical bug caused by the "unusual" quotes `’ ’`, it crashes the plugin even under "normal" mode without the remote connection.

Thank you to bring it up! I'll try to fix it as soon as possible.

**Comment by babyraging** [comment]
The newer version should've fixed this issue. Feel free to reopen if anything goes wrong.

**Comment by ErickHernandez** [comment]
Hi @babyraging  happy to know that I helped a little bit. The new version works like a charm and doesn't affect vscode anymore. Thanks!:)
