### ISSUE TITLE
Bison syntax not fully supported

### ISSUE THREAD

**Issue by orlensky** [babyraging/yash#18]
Hello,

I use dashes is non-terminal symbol names in my grammar. `yash` considers this an error.

I was a little bit surprised about that, since `bison` has no problems with interpreting the grammar. According to `bison` manual dashes are not supported in POSIX `yacc` syntax - they are a GNU extension.

> [https://www.gnu.org/software/bison/manual/html_node/Symbols.html](https://www.gnu.org/software/bison/manual/html_node/Symbols.html)
> Symbol names can contain letters, underscores, periods, and non-initial digits and dashes. Dashes in symbol names are a GNU extension, incompatible with POSIX Yacc.

I am not sure if this `yash` aims to be compatible with POSIX (`yacc`) only or also support GNU extensions syntax (`bison`), but according to the README the goal is to support both (_lex/yacc and flex/bison_).

**Comment by babyraging** [comment]
Hi @orlensky, thank you for the issue.

I'm sorry that it gives you the error, it shouldn't. And yes, we support bison as well and not only POSIX yacc.

The reason for the error is that I didn't actually read the bison manual entirely which means this extension will not be 100% compatible to it. It just would require too much time. 

I mainly solve problems and update when issues are raised by users. For this thank you for raise it up!

I can surely add the dash in the grammar and publish it within the week.

**Comment by orlensky** [comment]
@babyraging thanks for a quick reply and thanks for a good job on the extension! It would be nice to see a fix in the near future. I can contribute this one if you are interested in accepting PRs.

**Comment by C-basstien** [comment]
Hi @babyraging,
I also noticed that named reference in bracet cause incorrect syntax highlighting in Bison.
https://www.gnu.org/software/bison/manual/html_node/Named-References.html
Thanks a lot for your work on this great extension.

**Comment by babyraging** [comment]
@orlensky @C-basstien 

Hi guys, sorry for the wait. I've been working on the update today and here is the result, is the syntax highlighting what you expect?

![image](https://user-images.githubusercontent.com/14004642/147247994-ea005160-69ca-4041-b9a3-d7ec2a8885f0.png)

If this is ok, I'll push to the marketplace.

thanks

**Comment by C-basstien** [comment]
@babyraging thank you for the update that look great! 
Does it work as well with the previous example? 
`exp[res]: exp[x] '+' {$left = $x;}[left] exp[right] { $res = $left + $right; }`

**Comment by orlensky** [comment]
@babyraging the update looks good. I can see that you've also tackled named references to semantic values. I am not sure however, if you took into account Typed Mid-Rule Actions I mentioned before (screenshot you presented does not show such syntax). Here is some example taken from GNU Bison manual (https://www.gnu.org/software/bison/manual/bison.html#Typed-Midrule-Actions):
```stmt:
  "let" '(' var ')'
    {
      $<context>$ = push_context (); // <-- note syntax here
      declare_variable ($3);
    }
  stmt
    {
      $$ = $6;
      pop_context ($<context>5);
    }
```
and
```stmt:
  "let" '(' var ')'
    <context>{                       // <-- and here
      $$ = push_context ();
      declare_variable ($3);
    }
  stmt
    {
      $$ = $6;
      pop_context ($5);
    }
```

**Comment by babyraging** [comment]
@C-basstien 

Now it works!
![image](https://user-images.githubusercontent.com/14004642/147596304-d35d9e14-db04-49e9-82bd-71a40ac03b89.png)


@orlensky wow, that is a feature I have never used. I have a question, what are the symbols that can be put inside the <...> ? Is it always `context` or is it actually a type that we have defined inside the `%union` block?

**Comment by C-basstien** [comment]
@babyraging Nice!  
Regarding typed midrule-actions, if I understand correctly, context can be replaced by the type of data you want to cast.  
By the way, token type don't need to be declared in the %union when using the following parameters
%language "c++"
%define api.value.type variant
https://www.gnu.org/software/bison/manual/html_node/C_002b_002b-Variants.html

**Comment by Jooarye** [comment]
![image](https://user-images.githubusercontent.com/42173961/160251980-f6f1e4b6-8237-47a2-9b6b-b8a357d18e58.png)
Sadly the precedence syntax is not supported. It throws errors like "Unexpected | symbol." due to not expecting %left or %right directives.

Fix would be appreciated.

**Comment by babyraging** [comment]
@Jooarye thanks for the issue.

Are you sure that this is correct bison/yacc syntax?

%left or %right must be declared before the %% %% tag

![image](https://user-images.githubusercontent.com/14004642/160252272-bce21985-dd14-46da-8f25-6839095c046d.png)

**Comment by Jooarye** [comment]
Thx for the fast reply bison does accept it this way, although it might not be the correct way. I'm gonna try your way!!

**Comment by babyraging** [comment]
@Jooarye no problem. Also a minor suggestion, characters inside double quotes are considered *token alias* e.g. ```"-"```. Character inside single quotes is considered *literal character token* e.g. ```'-'```

**Comment by Jooarye** [comment]
Thx for the suggestion but that shouldn't be an issue since they are supposed to be tokens.
