### ISSUE TITLE
[Bug] Token alias is being ignored

### ISSUE THREAD

**Issue by X39** [babyraging/yash#2]
## Summary
Aliasing a Token and using that aliased token will result in the token being marked as error.
It also is not having a special Syntax-Highlighting nor is the tooltip displayed.

## Steps to Reproduce

1.  Create a file called eg. `file.y`
2. Paste the code at the end of this section into it
3. * YST_TEST is marked as unused
    * "test" is missing tooltip

## Expected

3. * YST_TEST is marked as being used
    * "test" is displaying a tooltip

## Example
![image](https://user-images.githubusercontent.com/1886428/82959007-10ecb000-9fb7-11ea-89c1-edf9a5493c75.png)

    %union { char* str; }
    %token <str> YST_TEST "test"
    %start start

    %%

    start: 'a'
         | "something"
         | "test"
         ;

    %%

## Related Documentation

https://www.gnu.org/software/bison/manual/html_node/Token-Decl.html

**Comment by babyraging** [comment]
Hi there, thank you very much for the issue, I'm glad that you provided an example code for me to test, thanks again :)

Yes, this is a feature that I wanted to add weeks ago but then... I forgot it.....

I will try to have it fixed by the weekend.
