### ISSUE TITLE
~~Please, Add .lex file extension support on the plugin ~~

### ISSUE THREAD

**Issue by MelvinG24** [babyraging/yash#20]
I have been working with some code samples from the web of Flex/Bison and the majority of those projects have the extension file of **.lex** instead of just **.l** which is quite annoying going file by file changing the extension form **.lex** to **.l** just for the plugin reconniced.

Thank you

**Comment by babyraging** [comment]
@MelvinG24 Hi Melvin, sure, I can add it in the next update which is in a couple of days, cheers.

**Comment by MelvinG24** [comment]
Thank you @babyraging, I thing I found were the extension file are located in the plugin and I already did my pull request
https://github.com/babyraging/yash/pull/21

**Comment by babyraging** [comment]
@MelvinG24 should be now fixed with the new update. Feel free to reopen for any issues.
