### ISSUE TITLE
"Symbol was not declared." on tokens defined with %precedence

### ISSUE THREAD

**Issue by DubiousDoggo** [babyraging/yash#5]
Tokens defined with `%precedence` are not detected as being declared.
Example:
```yacc
%precedence token1
%precedence token2
%%
rule1: token1 token2
```
Gives the error `Symbol was not declared.` for both tokens, although the code is accepted by bison.

Tested on:
Yash 0.2.5
GNU bison 3.7

**Comment by DubiousDoggo** [comment]
After digging though the code a bit I think this could be fixed by adding a case for `%precedence` here:
https://github.com/babyraging/yash/blob/66face2700c19ec8dcfc87424bd0a2df7ebd93d2/src/languages/parser/yaccParser.ts#L218-L223

**Comment by Sceriffo** [comment]
@DubiousDoggo thanks for the issue. 

Yes, it seems that we skipped one case. It will be fixed soon in the next version.

**Comment by babyraging** [comment]
@DubiousDoggo sorry for the late response.

Indeed, great find, that one line case is all we need. 
A new patch will be released soon fixing the problem.
